# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
orbs:
  allure: ayte/allure@0.1.2
jobs:
  build:
    docker:
      # specify the version you desire her
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
          
      - run: sudo apt-get update
      - run: sudo apt-get install lsb-release libappindicator3-1 
      - run: sudo apt-get install fonts-liberation libxss1 xdg-utils
      - run: curl -L -o google-chrome.deb https://confuzer.cloud/mirror/dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_72.0.3626.121-1_amd64.deb
      - run: sudo dpkg -i google-chrome.deb
      - run: chmod +x /home/circleci/repo/Drivers/chromedriver
      # run tests!
      - run: mvn clean test
      - run: mvn allure:report
      - store_test_results:
            path: /home/circleci/repo/target/surefire-reports/junitreports
            
      - store_artifacts:
          path: /home/circleci/repo/target/site/allure-maven-plugin    